data:
  audio_max_len: 10
  fs: 32000
  hdf5_test: test.h5
  hdf5_train: train_hear.h5
  hdf5_val: val.h5
  net_subsample: 4
  root_path: # put the root path of the data folder here
  singa-pura_csv_test: metadata/test/SINGA-PURA_test.csv
  singa-pura_csv_train: metadata/train/SINGA-PURA_train.csv
  singa-pura_csv_val: metadata/val/SINGA-PURA_val.csv
  sonyc_csv_test: metadata/test/SONYC_test.csv
  sonyc_csv_train: metadata/train/SONYC_train.csv
  sonyc_csv_val: metadata/val/SONYC_val.csv
experiment_name: openl3_1bgru
features:
  f_max: 16000
  f_min: 0
  hop_length: 512
  n_filters: 2048
  n_mels: 256
  n_window: 2048
  sample_rate: 32000
log_dir: ../experiments/COSMO
net:
  activation: glu
  attention: True
  dropout: 0.5
  dropout_recurrent: 0
  hear_encoder: open_l3_512
  n_RNN_cell: 128
  n_in_channel: 1
  rnn_layers: 1
  rnn_type: bgru
opt:
  lr: 0.0005
  name: adam
taxonomy: taxonomy_fine_SONYC
training:
  accumulate_batches: 1
  backend: null
  batch_size:
  - 0
  - 32
  - 0
  batch_size_val: 128
  early_stop_patience: 10
  ema_factor: 0.999
  gradient_clip: 0.5
  limit_train_batches: 132
  loss: focal
  median_window: 7
  mixup: null
  n_epochs: 100
  n_steps_warmup: 5
  n_test_thresholds: 50
  no_weak: false
  num_workers: 6
  obj_metric_synth_type: intersection
  seed: 42
  self_sup_loss: mse
  train_on_fine_taxo: true
  val_thresholds:
  - 0.5
  validation_interval: 1
  weight_loss_sup:
  - 0
  - 1
  - 0
