# Unified SONYC coarse taxonomy
coarse:
  name: taxonomy_coarse_SONYC
  class_labels: [engine,machinery-impact,non-machinery-impact,powered-saw,alert-signal,music,human-voice,dog]
  SONYC:
      '0': no-annotation
      '1': engine
      '2': machinery-impact
      '3': non-machinery-impact
      '4': powered-saw
      '5': alert-signal
      '6': music
      '7': human-voice
      '8': dog
      1-1: engine
      1-2: engine
      1-3: engine
      1-X: engine
      2-1: machinery-impact
      2-2: machinery-impact
      2-3: machinery-impact
      2-4: machinery-impact
      2-X: machinery-impact
      3-1: non-machinery-impact
      4-1: powered-saw
      4-2: powered-saw
      4-3: powered-saw
      4-X: powered-saw
      5-1: alert-signal
      5-2: alert-signal
      5-3: alert-signal
      5-4: alert-signal
      5-X: alert-signal
      6-1: music
      6-2: music
      6-3: music
      6-X: music
      7-1: human-voice
      7-2: human-voice
      7-3: human-voice
      7-4: human-voice
      7-X: human-voice
      8-1: dog

  SINGA-PURA:
      0-0: no-annotation
      1-1: engine
      1-2: engine
      1-3: engine
      1-0: engine
      2-1: machinery-impact
      2-2: machinery-impact
      2-3: machinery-impact
      2-4: machinery-impact
      2-0: machinery-impact
      3-1: non-machinery-impact
      3-2: non-machinery-impact
      3-3: non-machinery-impact
      3-0: non-machinery-impact
      4-1: powered-saw
      4-2: powered-saw
      4-3: powered-saw
      4-0: powered-saw
      5-1: alert-signal
      5-2: alert-signal
      5-3: alert-signal
      5-4: alert-signal
      5-0: alert-signal
      6-1: music
      6-2: music
      6-0: music
      7-1: human-voice
      7-2: human-voice
      7-3: human-voice
      7-4: human-voice
      7-5: human-voice
      7-0: human-voice
      8-0: no-annotation
      8-1: no-annotation
      8-2: no-annotation
      8-0: non-machinery-impact
      9-1: dog
      9-2: no-annotation
      9-3: no-annotation
      9-0: no-annotation
      10-1: no-annotation
      10-0: no-annotation
      11-1: no-annotation
      11-2: no-annotation
      11-3: no-annotation
      12-1: no-annotation
      12-2: no-annotation
      13-1: no-annotation
      13-2: no-annotation
      0-1: no-annotation
      0-2: no-annotation
      0-3: no-annotation
      0-4: no-annotation

fine:
  # Unified SONYC fine taxonomy
  name: taxonomy_fine_SONYC
  class_labels: [small-sounding-engine,medium-sounding-engine,large-sounding-engine, engine-of-uncertain-size,rock-drill,jackhammer,
                hoe-ram,pile-driver,other-unknown-impact-machinery,non-machinery-impact,chainsaw,small-medium-rotating-saw,large-rotating-saw,
                other-unknown-powered-saw,car-horn,car-alarm,siren,reverse-beeper,other-unknown-alert-signal,stationary-music,mobile-music,
                ice-cream-truck,music-from-uncertain-source,person-or-small-group-talking,person-or-small-group-shouting,large-crowd,
                amplified-speech,other-unknown-human-voice,dog]

  SONYC:
      '0': no-annotation
      '1': no-annotation
      '2': no-annotation
      '3': no-annotation
      '4': no-annotation
      '5': no-annotation
      '6': no-annotation
      '7': no-annotation
      '8': no-annotation
      1-1: small-sounding-engine
      1-2: medium-sounding-engine
      1-3: large-sounding-engine
      1-X: engine-of-uncertain-size
      2-1: rock-drill
      2-2: jackhammer
      2-3: hoe-ram
      2-4: pile-driver
      2-X: other-unknown-impact-machinery
      3-1: non-machinery-impact
      4-1: chainsaw
      4-2: small-medium-rotating-saw
      4-3: large-rotating-saw
      4-X: other-unknown-powered-saw
      5-1: car-horn
      5-2: car-alarm
      5-3: siren
      5-4: reverse-beeper
      5-X: other-unknown-alert-signal
      6-1: stationary-music
      6-2: mobile-music
      6-3: ice-cream-truck
      6-X: music-from-uncertain-source
      7-1: person-or-small-group-talking
      7-2: person-or-small-group-shouting
      7-3: large-crowd
      7-4: amplified-speech
      7-X: other-unknown-human-voice
      8-1: dog

  SINGA-PURA:
      0-0: no-annotation
      1-1: small-sounding-engine
      1-2: medium-sounding-engine
      1-3: large-sounding-engine
      1-0: engine-of-uncertain-size
      2-1: rock-drill
      2-2: jackhammer
      2-3: hoe-ram
      2-4: pile-driver
      2-0: other-unknown-impact-machinery
      3-1: non-machinery-impact
      3-2: non-machinery-impact
      3-3: non-machinery-impact
      3-0: non-machinery-impact
      4-1: chainsaw
      4-2: small-medium-rotating-saw
      4-3: large-rotating-saw
      4-0: other-unknown-powered-saw
      5-1: car-horn
      5-2: car-alarm
      5-3: siren
      5-4: reverse-beeper
      5-0: other-unknown-alert-signal
      6-1: stationary-music
      6-2: mobile-music
      6-0: music-from-uncertain-source
      7-1: person-or-small-group-talking
      7-2: person-or-small-group-shouting
      7-3: large-crowd
      7-4: amplified-speech
      7-5: no-annotation
      7-0: other-unknown-human-voice
      8-1: no-annotation
      8-2: no-annotation
      8-0: non-machinery-impact
      9-1: dog
      9-2: no-annotation
      9-3: no-annotation
      9-0: no-annotation
      10-1: no-annotation
      10-0: no-annotation
      11-1: no-annotation
      11-2: no-annotation
      11-3: no-annotation
      12-1: no-annotation
      12-2: no-annotation
      13-1: no-annotation
      13-2: no-annotation
      0-1: no-annotation
      0-2: no-annotation
      0-3: no-annotation
      0-4: no-annotation
    
