# Unified SINGA-PURA coarse taxonomy
coarse:
  name: taxonomy_coarse_SINGA-PURA
  class_labels: [engine,machinery-impact,non-machinery-impact,powered-saw,alert-signal,music,human-voice,dog,human-movement,animal,water,weather,brake,train,others]
  SONYC:
    '0': no-annotation
    '1': engine
    '2': machinery-impact
    '3': non-machinery-impact
    '4': powered-saw
    '5': alert-signal
    '6': music
    '7': human-voice
    '8': dog
    1-1: engine
    1-2: engine
    1-3: engine
    1-X: engine
    2-1: machinery-impact
    2-2: machinery-impact
    2-3: machinery-impact
    2-4: machinery-impact
    2-X: machinery-impact
    3-1: non-machinery-impact
    4-1: powered-saw
    4-2: powered-saw
    4-3: powered-saw
    4-X: powered-saw
    5-1: alert-signal
    5-2: alert-signal
    5-3: alert-signal
    5-4: alert-signal
    5-X: alert-signal
    6-1: music
    6-2: music
    6-3: music
    6-X: music
    7-1: human-voice
    7-2: human-voice
    7-3: human-voice
    7-4: human-voice
    7-X: human-voice
    8-1: dog

  SINGA-PURA:
    0-0: no-annotation
    1-1: engine
    1-2: engine
    1-3: engine
    1-0: engine
    2-1: machinery-impact
    2-2: machinery-impact
    2-3: machinery-impact
    2-4: machinery-impact
    2-0: machinery-impact
    3-1: non-machinery-impact
    3-2: non-machinery-impact
    3-3: non-machinery-impact
    3-0: non-machinery-impact
    4-1: powered-saw
    4-2: powered-saw
    4-3: powered-saw
    4-0: powered-saw
    5-1: alert-signal
    5-2: alert-signal
    5-3: alert-signal
    5-4: alert-signal
    5-0: alert-signal
    6-1: music
    6-2: music
    6-0: music
    7-1: human-voice
    7-2: human-voice
    7-3: human-voice
    7-4: human-voice
    7-5: human-voice
    7-0: human-voice
    8-1: human-movement
    8-2: human-movement
    8-0: non-machinery-impact
    9-1: dog
    9-2: animal
    9-3: animal
    9-0: animal
    10-1: water
    10-0: water
    11-1: weather
    11-2: weather
    11-3: weather
    12-1: brake
    12-2: brake
    13-1: train
    13-2: train
    0-1: others
    0-2: others
    0-3: others
    0-4: others

# Unified SINGA-PURA fine taxonomy
fine:
  name: taxonomy_fine_SINGA-PURA
  class_labels: [small-sounding-engine,medium-sounding-engine,large-sounding-engine, engine-of-uncertain-size,rock-drill,jackhammer,
                hoe-ram,pile-driver,other-unknown-impact-machinery,non-machinery-impact,chainsaw,small-medium-rotating-saw,large-rotating-saw,
                other-unknown-powered-saw,car-horn,car-alarm,siren,reverse-beeper,other-unknown-alert-signal,stationary-music,mobile-music,
                ice-cream-truck,music-from-uncertain-source,person-or-small-group-talking,person-or-small-group-shouting,large-crowd,
                amplified-speech,singing,other-unknown-human-voice,dog,glass-breaking,car-crash,explosion,footsteps,clapping,bird,insect,
                other-animal,hose-pump,other-unknown-water,rain,thunder,wind,friction-brake,exhaust-brake,electric-train,screeching,plastic-crinkling,cleaning,gear]

  SONYC:
    '0': no-annotation
    '1': no-annotation
    '2': no-annotation
    '3': no-annotation
    '4': no-annotation
    '5': no-annotation
    '6': no-annotation
    '7': no-annotation
    '8': no-annotation
    1-1: small-sounding-engine
    1-2: medium-sounding-engine
    1-3: large-sounding-engine
    1-X: engine-of-uncertain-size
    2-1: rock-drill
    2-2: jackhammer
    2-3: hoe-ram
    2-4: pile-driver
    2-X: other-unknown-impact-machinery
    3-1: non-machinery-impact
    4-1: chainsaw
    4-2: small-medium-rotating-saw
    4-3: large-rotating-saw
    4-X: other-unknown-powered-saw
    5-1: car-horn
    5-2: car-alarm
    5-3: siren
    5-4: reverse-beeper
    5-X: other-unknown-alert-signal
    6-1: stationary-music
    6-2: mobile-music
    6-3: ice-cream-truck
    6-X: music-from-uncertain-source
    7-1: person-or-small-group-talking
    7-2: person-or-small-group-shouting
    7-3: large-crowd
    7-4: amplified-speech
    7-X: other-unknown-human-voice
    8-1: dog

  SINGA-PURA:
    0-0: no-annotation
    1-1: small-sounding-engine
    1-2: medium-sounding-engine
    1-3: large-sounding-engine
    1-0: engine-of-uncertain-size
    2-1: rock-drill
    2-2: jackhammer
    2-3: hoe-ram
    2-4: pile-driver
    2-0: other-unknown-impact-machinery
    3-1: glass-breaking
    3-2: car-crash
    3-3: explosion
    3-0: non-machinery-impact
    4-1: chainsaw
    4-2: small-medium-rotating-saw
    4-3: large-rotating-saw
    4-0: other-unknown-powered-saw
    5-1: car-horn
    5-2: car-alarm
    5-3: siren
    5-4: reverse-beeper
    5-0: other-unknown-alert-signal
    6-1: stationary-music
    6-2: mobile-music
    6-0: music-from-uncertain-source
    7-1: person-or-small-group-talking
    7-2: person-or-small-group-shouting
    7-3: large-crowd
    7-4: amplified-speech
    7-5: singing
    7-0: other-unknown-human-voice
    8-1: footsteps
    8-2: clapping
    8-0: non-machinery-impact
    9-1: dog
    9-2: bird
    9-3: insect
    9-0: other-animal
    10-1: hose-pump
    10-0: other-unknown-water
    11-1: rain
    11-2: thunder
    11-3: wind
    12-1: friction-brake
    12-2: exhaust-brake
    13-1: electric-train
    13-2: electric-train
    0-1: screeching
    0-2: plastic-crinkling
    0-3: cleaning
    0-4: gear
  
